### ISSUE TITLE
Metrics revisiting

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2162]
# Overview

This is a grand issue, that will probably need to be fixed with multiple PRs. Self-reported metrics are unreliable. They have a number of issues:

- We cannot map back to individual examples. As such, at training time, we don't have any way of knowing things like `ppl` on a given task
- At validation time, we solve this by running each task in serial.
- We aren't sure how to combine them in a distributed setting. As a result, we opt to run validation only on the primary worker, while all the secondary workers just sit idle. This is extremely wasteful of expensive GPU time. If we could fix the metrics averaging, then we could easily shard the validation set across all the workers

# Part 1: Metric object

We need a generic Metric object, as well as a few variants. It should define a very simple interface:

```python
class Metric(object):
    @abstractmethod
    def report(self) -> Number:
         pass

    def __str__(self) -> str:
        return '{:.4g}'.format(self.report())

    def __repr__(self) -> str:
        return '{}({:.4g})'.format(str(self.__class__), self.report())

class SumMetric(Metric):
    # keeps a running sum
    def __init__(self, value: Number)
    def __add__(self, other: SumMetric) -> SumMetric
    def report(self) -> Number

class AverageMetric(Metric):
    def __init__(self, value: Number, denom: Integer)
    def __add__(self, other: AverageMetric) -> AverageMetric
         # Combines two metrics. This should create a new metric, which has the
         # numerator and denominator combined
    def report(self) -> Number
        # should "render" the object, as in return 
 ```

Most things will just use AverageMetric. Something like PPLMetric can be implemented via a call to `exp()` in the `report()` call.

The point of having clear semantics for *combining* metrics

## Requirements

- [x] I believe Metric should be immutable. We should encourage *combining* metrics rather than editing them.
- [x] Metric should be happy taking item tensors and converting them. It should throw an error if they aren't scalars though.
- [x] Metric should live in metrics.py
- [x] Metric should be strongly typed.
- [x] Metric should be well-documented
- [x] Must have unit tests

Maybe:
- [ ] Define comparators like > or < for Metrics, it could be super convenient in train_model.

# Part 2: Cleanup of metrics.py

With the AverageMetric well defined, we can now use it in metrics.py to clean up a lot of the tracking behavior. All of the `_cnt` madness in the current stuff should be removed and added for Metrics.

# Part 3: Handling metrics

Things that employ `report()` should be comfortable with being returned a dict of Metric objects. This particularly will require particularly upgrading train_model and eval_model. The combining metrics bit should be upgraded to use the Metric's builtin combine (`__add__`).

Next, Metrics should be able to return part of the return for `eval_step` and `train_step` in TA. If a *list* of metrics is passed as an item in the `Output`, it should be the same length of the number of examples in the batch. This should be asserted in TA.

We may wish to also return single (non-list) Metrics as part of the `Output`. The semantics of this *could* be accumulating them in a local object like the current `self.metrics`. This may need to be debated in the group

# Part 4: Upgrading agents

- [ ] Upgrade TA, TRA, TGA, TCA to use metrics for everything they use.
- [ ] If it's a metric that makes sense as per-example metric should be moved into the Output objects
- [ ] *Anywhere* that uses round_sigfigs that is being upgraded for metrics should *drop the round_sigfigs*.
- [ ] A lot of the logic in current `report()` implementations should be replaced by simple metric returns.
- [ ] For TGA, a specialized PPL agent that does the exponentiated average in its report will be necessary
- [ ] Ideally, we'd write simple unit tests that verify averages are combining correctly

# Unknown bits

It wouldn't be a good mission if it were entirely planned. There probably a number of tricky areas:

- HogWild probably has some messiness
- Printing may have some trouble.
- JSON dumping in places is also probably an issue.
